MovieWorld/urls.py
# https://www.youtube.com/watch?v=qgGIqRFvFFk&list=PL6gx4Cwl9DGBlmzzFcLgDhKTTfNLfX1IK

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from companies import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
    path('stocks/', views.StockList.as_view())
]

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    path('', views.IndexView.as_view(), name='index'),

    path('register/', views.UserFormView.as_view(), name='register'),

    # /music/1
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    # /music/album/add
     path('album/add', views.AlbumCreate.as_view(), name='album-add'),

    # music/album/2
     path('album/<int:pk>/', views.AlbumUpdate.as_view(), name='album-update'),

    # music/album/2/delete
    path('album/<int:pk>/delete/', views.AlbumDelete.as_view(), name='album-delete')



]

companies/models.py
from django.db import models


class Stock(models.Model):
  ticker = models.CharField(max_length=10)
  open = models.FloatField()
  close = models.FloatField()
  volume = models.IntegerField()

  def __str__(self):
    return self.ticker

music/models.py
from django.db import models
from django.urls import reverse

class Album(models.Model):
    artist = models.CharField(max_length=200)
    album_title = models.CharField(max_length=200)
    genre = models.CharField(max_length=200)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music/detail.html', kwargs={'pk': self.pk})

    def __str__(self):
        return self.artist + '-' + self.album_title + '-' + self.genre + '-' + self.album_logo


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=200)
    file_type = models.CharField(max_length=100)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title + ' - ' + self.file_type

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
  pssword = forms.CharField(widget=forms.PasswordInput)
  class Meta:
    model = User
    fields = ['username', 'email', 'password']

companies/views.py
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import Stock
from .serializers import StockSerializer

# Lists all stocks or create a new
# stocks/1
class StockList(APIView):

  def get(self, request):
    stock = Stock.objects.all()
    serializer = StockSerializer(stock, many=True)
    return Response(serializer.data)

  def post(self):
    pass

music/views.py
from django.views import generic
from .models import Album, Song
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views import generic
from django.views.generic import TemplateView
from .forms import UserForm


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_album'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class UserFormView(TemplateView):
    form_class = UserForm
    template_name = 'music/register_form.html'

    # display blank form
    def get(self, request):
      form = self.form_class(None)
      return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
      form = self.form_class(request.POST)
      if form.is_valid():
        user = form.save(commit=False)

    # clean normalized data
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()

    # return User objects if credentials are correct
        user = authenticate(username=username, password=password)
        if user is not None:
          if user.is_active:
            login(request, user)
            return redirect('music:index')

      return render(request, self.template_name, {'form': form})

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title%}Add new Album {% endblock %}
<!--{% block album_active %}active {% endblock %}-->

{% block body %}
<div class="container_fluid">
  <div class="row">
    <div class="col-sm-12 col-md-7">
      <div class="panel panel-default">
        <div class="panel-body">
          <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
            {% csrf_token%}
            {% include 'music/form-template.html' %}
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">
                  Submit
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}MovieWorld{% endblock %}</title>
    {% load staticfiles %}
    <link type="text/css" rel="stylesheet" href="{% static 'music/styles.css' %}"/>
    <link type="text/css" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--header-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">MovieWorld</a>
        </div>
        <!--Items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true">&nbsp;AddAlbum</span>
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true">&nbsp;Logout</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body%}
{% endblock%}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %} Album Details {% endblock %}
{% load static %}
{% block body %}
    <!--<img src="{% static 'music/images/bird.jpg' %}">-->
    <img src="{{album.album_logo.url}}"/>
    <h2>Album Title: {{album.album_title}}</h2>
    <h3>Album artist: {{album.artist}}</h3>

    {% if error_msg %}
        <p><strong>{{error_msg}}</strong></p>
    {% else %}
    <form action="{% url 'music:detail' album.id %}" method="post">
        {% csrf_token %}
        {% for song in album.song_set.all %}
            <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{song.id}}"/>
            <label for="song{{ forloop.counter }}">
                {{song.song_title}}
                {% if song.is_favorite %}
                    <img src="{% static 'music/images/star.png' %}" alt="my image"/>
                {% endif %}
            </label><br>
        {% endfor %}
        <input type="submit" value="Favorite">
    </form>
    {% endif %}
{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{field.errors}}</span>
    </div>
    <label class="control-label col-sm-2">{{field.label_tag}}</label>
    <div class="col-sm-10">{{field}}</div>
  </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block body %}
<div class="container-fluid">
  <div class="row">
    {% if all_album %}
        {% for album in all_album %}
          <div class="col-sm-4 col-md-2">
            <div class="thumbnail">
              <a href="{% url 'music:detail' album.id %}">
                <img src="{{album.album_logo.url}}" alt="">
              </a>
              <div class="caption">
                <h2>{{album.album_title}}</h2>
                <h4>{{album.artist}}</h4>
                <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                <form action="{% url 'music:album-delete' album.id %}" method="post" style="display:inline" >
                  {% csrf_token %}
                    <input type="hidden" name="album_id" value="{{album.id}}">
                    <button type="submit" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form>
              </div>
            </div>
          </div>
        {% endfor %}
    {% else %}
      <h3>No Album exists!</h3>
    {% endif %}
  </div>
</div>
{% endblock %}

music/templates/music/register_form.html
{% extends 'music/base.html' %}
{% block title%} Register {% endblock %}
<!--{% block album_active %}active {% endblock %}-->

{% block body %}
<div class="container_fluid">
  <div class="row">
    <div class="col-sm-12 col-md-7">
      <div class="panel panel-default">
        <div class="panel-body">
            <h3>Create a New Account</h3>
          <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
            {% csrf_token%}
            {% include 'music/form-template.html' %}
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">
                  Submit
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}